### ISSUE TITLE
Its Automaticly Selecting The First Item Value

### ISSUE THREAD

**Issue by MirazMac** [xdan/autocomplete#22]
I'm using
$('#homeInput').on('selected.xdsoft', function(event, item){
$(this).val(selected.xdsoft.item.value);
  $("#searchform").submit();
});
Its working fine but the problem is even if user doesn't select any suggestion and press enter its automatically selecting the first suggestion item value :(

**Comment by eirtaza** [comment]
I am facing the same problem.

even after autoselect:false,

**Comment by ilkin007** [comment]
The same thing...
